### ISSUE TITLE
Change progress problem

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [danielstern/ngAudio#101]
Hi,

I'm working wwith a jhipster project and trying to work with ngAudio. Everything works fine except changing progress.
I have my range input bind on the progress of my sound file

```
<input class='form-control' type=range min=0 max=1 step=0.01
                                ng-model='dictationAudio.progress'/>
```

In my controller, the audio is loaded like this:

```
$scope.dictationAudio = ngAudio.load($scope.sentence.dictationPath);
```

When I click on my range bar, surprisingly I receive to notifications on progress variable change : (I have a watch on this):

```
$scope.$watch('dictationAudio.progress', function(){
        console.log('watch dictationAudio.progress:', $scope.dictationAudio.progress);
 });
```

Each time I click on range bar, I have the following output on console:

```
watch dictationAudio.progress: 0.12
watch dictationAudio.progress: 0
watch dictationAudio.progress: 0.13
watch dictationAudio.progress: 0
```

(The 0 values arrives just after the "good" value)

Do you see, where the problem can come from?

Thank you in advance!

**Comment by danielstern** [comment]
Hey @natalia-pokrovskaya 

Could you share a JSFiddle with the bug reproduced?

Cheers
DS

**Comment by natalia-pokrovskaya** [comment]
Hello @danielstern  ,

I'm sorry, I have no experience with this tool and I can't make it work. Do you have I little JsFiddle template with ngAudio integrated so I can modify it to reproduce my bug?

Thanks you in advance!

**Comment by buruno** [comment]
hey, after struggling with this issue for days and I guess I finally found an explanation (no solution, tho, as it seems to be a server/browser issue): http://stackoverflow.com/questions/8088364/html5-video-will-not-loop

**Comment by AjejeBrazorf** [comment]
I have the same issue, did you find out how to resolve it?

**Comment by eugenedw** [comment]
I'm having this same problem. From what I can tell, the issue has something to do with the $watch activity defined in the checkWatchers() method. Here (in the latest version), the if-then-else that handles $observeProperties appears to be resetting progress, not based upon the setting of the slider, but either 0 (audioObject.progress = 0) or to the tempProgress obtained from dividing audio.currentTime by audio.duration (audio.currentTime/audio.duration). 

This process is firing every second so that no matter what the progress is adjusted to using the slider, the progress will always be reset to 0. I'm still testing this, but feel that the root cause is somewhere here.

**Comment by natalia-pokrovskaya** [comment]
Hi! 

In my case the problem related to developer console (F12) which was open in my browser... When the console is closed everything works fine...  Strange... 
@eugenedw does your have an opened console as well?

**Comment by delacongithub** [comment]
I have found this issue to be apparent as well. My method of testing was slightly different:
```
Object.defineProperty(this.audiosource, "progress", {
configurable:true,
enumerable:true,
set: function(val){
    console.log(val);
    this._progress = val;
},
get: function(){
    return this._progress;
}
});

```

I am unsure on the best way to correct this, but just adding this is still apparent 2 months later

**Comment by delacongithub** [comment]
The issue I believe is to do with the Audio source, if the Audio source isn't delivered in a single "chunk", the progress attribute seems to default to 0, but when delivered using a Partial Content (HttpStatus 206), with a range, it appears to work.

**Comment by delacongithub** [comment]
Just adding a new note, with the Partial Content the Range works, though the play sticks and won't proceed

**Comment by delacongithub** [comment]
Figured it out, the issue is to do with a rounding error on the checkWatchers function, I found that whenever the progress attempted to be updated, it kept rounding to 2 decimal places with my audio, which stayed at 0, and reset the currentTime to 0 as such. Adding toPrecision prevents the JS engine from rounding down.
