### ISSUE TITLE
Play error, Uncaught (in promise) DOMException: The element has no supported sources. 

### ISSUE THREAD

**Issue by tqcenglish** [danielstern/ngAudio#148]
1. audio.play() ok
2. audio.stop() ok
3. audio.play() error

https://github.com/danielstern/ngAudio/commit/55539a4af3b79264dccd5318db09ae9774f55eba

**Comment by elliot-a** [comment]
I'm getting the same bug - I did update angular to 1.5.7 - could that be related?

**Comment by timo-klarshift** [comment]
Also using 1.5.7 and it is not working, eg is like tqcenglish describes

**Comment by tlenex** [comment]
same issue here

**Comment by danielstern** [comment]
Woops. Can someone make a PR reverting that change and it will be merged ASAP

**Comment by rib3** [comment]
Created #149 to revert 55539a4.

Please merge, publish, etc when you get a chance.

**Comment by mittalabhas1** [comment]
@danielstern care to merge this soon please?

**Comment by rib3** [comment]
@danielstern @AmitMY, could you tag and npm publish (`1.7.3`?)

**Comment by AmitMY** [comment]
@rib3 I published a new NPM version
https://www.npmjs.com/package/angular-audio

@danielstern please take the lead on the NPM project

**Comment by danielstern** [comment]
@AmitMY Sounds good, how exactly is that done? My npm username is danielstern

**Comment by rib3** [comment]
@danielstern - Can you tag current `master` as `1.7.3`? (So there is no discrepancy between github and the npm versions.)

**Comment by AmitMY** [comment]
@danielstern You are now an owner (https://www.npmjs.com/package/angular-audio)
To do stuff, you open a bash window, authorize your user once, and then forever just write `npm publish`.

Please note that you can't publish 1 version twice, so if you fuck the version up, you have to go through removing the first release. (this is why NPM has 1.7.3 - because I fucked up 1.7.1,  and didnt know I can remove that version..)

**Comment by danielstern** [comment]
Anyone want to tackle this? Let me know and I'll sort you out with admin privelegaes

**Comment by danielstern** [comment]
1.7.3 is up
