### ISSUE TITLE
Only One Audio File Plays

### ISSUE THREAD

**Issue by kmccullough** [danielstern/ngAudio#187]
I'm using the latest in master, but I've tracked down the problem to this commit https://github.com/danielstern/ngAudio/commit/d6b1c632606076b0840cfc8563827dc018b92df5

Only one audio file appears to be loading.

This plunker displays the problem https://plnkr.co/edit/KHXLZX?p=preview . Comment out the problem library and uncomment out the working one to see the working desired result.

**Comment by kmccullough** [comment]
If I decide to fix this, should I add a configuration option to use ngAudioDomUid, on request, but not by default? I'm not clear on the usefulness of the Uid.

**Comment by jsheffers** [comment]
I'm having the same issue here. I've got a component that is being ng-repeated which then passes an audio file (1 per repeat) to the controller and when all three are loaded on the page only the last one plays.

After looking into this I realized that the audio object comes back fine, but one value is incorrect.  The ```src``` value of the audio object is wrong.  There are two other instances of the URL in the audio object and they are set properly (id to name one).   Any ideas how to fix this?

**Comment by javascope** [comment]
The reason for this issue is the constant ngAudioDomUid. If you use the entered url instead of ngAudioDomUid in 'remoteAudioFindingService' service, the issue is resolved.

**Comment by john-lieb** [comment]
As @javascope pointed out would the following not be an appropriate fix?

@kmccullough I used your plunker as an example.
https://plnkr.co/edit/Fsncct5jAuYjTRu0BAaO?p=preview

I modified ngAudio-d6b1c63.js (same as current master branch angular.audio.js). Instead of the remoteAudioFindingService using the constant ngAudioDomUid, use the url as the id of the Audio element.

Inspecting the page I can see multiple audio tags being created
<audio id="http://www.noiseaddicts.com/samples_1w72b820/3707.mp3" src="http://www.noiseaddicts.com/samples_1w72b820/3707.mp3" style="display: none;"></audio><audio id="http://www.noiseaddicts.com/samples_1w72b820/4927.mp3" src="http://www.noiseaddicts.com/samples_1w72b820/4927.mp3" style="display: none;"></audio>

This should not affect #140.

**Comment by john-lieb** [comment]
Created a new plunker https://plnkr.co/edit/Fsncct5jAuYjTRu0BAaO?p=preview. Using the DomUid generator in combination with a dictionary object (using the url as the lookup).
