### ISSUE TITLE
Fix Unlock  Function's Unexpected Behaviours

### ISSUE THREAD

**Issue by janv** [danielstern/ngAudio#43]
Here: https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L101

A global event handler for the click event installed with the result that:

- After loading an audio-file and playing it, the first click _anywhere_ in the window stops playback
- Sometimes, `audio` in the event handler becomes undefined, the click handler then causes errors. I have not been able to determine the exact circumstances for this.

Is this some kind of mistake? If not, how can prevent global click events from pausing the playback?

**Comment by janv** [comment]
Related #16, #33

**Comment by danielstern** [comment]
Hey @janv This is an issue I've been looking at for a while. It occurs mostly on iPhones in my experience and is tricky to troubleshoot. I've noticed it tends to occur most often in Safari 7.
I don't have any solutions at this time. The Twiddle function as referenced in the blob was hastily implemented and perhaps could be rewritten to avoid the bug mentioned above. If so, please feel free to put together a pull request and submit it.

Cheers,
DS

**Comment by janv** [comment]
I'm still thinking about this and reading #16 and #33 I understand the reasons.
So it seems the only way to prevent the observed issues is to 

- preload using `ngAudio.load`
- Trigger a play using a button or link

That way, triggering playback will at the same time get rid of the event handler.

**Comment by danielstern** [comment]
It seems like that implementation could work. The challenge I have found is to getting a consistent solution on all devices. Currently, this library supports IOS7, IOS8 (phones and tablet) and the most popular Android implementation. 

I've found that JPlayer actually does this well but I haven't been able to determine what in the code is fixing the bug.

Cheers

**Comment by janv** [comment]
I've been thinking about this. I don't consider the current behavior a good idea because it's a workaround for a behavior that developers of mobile browsers put in place specifically to prevent sites from draining data without the users consent.

It would be better to inform users of ngAudio about this in the Readme and tell them how to work around this limitation on their own, by telling them how to properly set up their event handlers in a way that the playback is triggered by a user event. As far as I can tell, that will work on mobile browsers and is in everybody's best interest.

Currently the library is simply buggy because of this workaround. As I said, I could reliably cause exceptions to bubble up in the event handler on `window`. And mobile users are screwed because they might inadvertently download a 12mb mp3.

**Comment by danielstern** [comment]
@janv That's fair. The behaviour is mostly implemented for this scenario:

Let's say you're making an MP3 player app with a playlist. The user starts song one, and when he clicks play the event fires at the same time, allowing the song to play as expected. But when the next song starts, it won't play because it hasn't been "unlocked." The user would have to click again to play the next song. This probably isn't the behavior the user will want.

The best solution here is to make the fix smarter, or add a flag allowing developers to disable this feature for certain files.

**Comment by danielstern** [comment]
Anyone want to take a crack at this one?

**Comment by ArTiSTiX** [comment]
I have no idea how to fix this... But you should add an option on load to ignore the Twiddle function, because not all developers care about iPhone & iPad.

And of course, if you don't find any better solution you should document this behaviour, explain the reasons. Thereby, developers who need to use this trick (like me) could anticipate the file loading when launching application by example.

**Comment by danielstern** [comment]
## Resolution

Added a new `unlock` boolean in the ngAudio global. Setting this to false will disable this functionality altogether.

https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L97
