### ISSUE TITLE
sound plays even after stopping

### ISSUE THREAD

**Issue by alexvnsky** [danielstern/ngAudio#6]
I use the following code to play a sound. 

``` javascript
   var playWarning;

    $scope.startPlayWarning = function() {
        // Don't start play if we are already playing
        if ( angular.isDefined(playWarning) ) return;

        ngAudio.play(appConfig.mp3_warning);

        playWarning = $interval(
            function() {
                ngAudio.play(appConfig.mp3_warning);
            },
            10000
        );
    };

    $scope.stopPlayWarning = function() {
        if (angular.isDefined(playWarning)) {
            ngAudio.stop(appConfig.mp3_warning);
            $interval.cancel(playWarning);
            playWarning = undefined;
        }
    };

    // Some code ...
    $scope.startPlayWarning();
```

But after scope destroy the melody continues to play

``` javascript
    $scope.$on("$destroy", function() {       
        $scope.stopPlayWarning();
    });
```

**Comment by srimal4you** [comment]
You can define audio playing function on rootScope. Then you can control audio function globally.

**Comment by crispconcepts** [comment]
If you would like the sound available globally, you don't need to add it to the rootScope. Nor should you be. You should create service to handle it and inject that service into any components that need access to it. In my case, it is housed inside an alert-service since the sound is tied directly to the alert.

`
// error sound effect
svc.alert.sound = ngAudio.load('assets/audio/beep.mp3');
svc.alert.sound.loop = true;
	
// view functions
svc.open = function (newMessage, newtitle, playSound, soundTimeout){
	console.log('alertSvc.open(...) called', newMessage, newtitle, playSound, soundTimeout);
	if(newMessage) svc.alert.message = newMessage;
	if(newtitle) svc.alert.class = newtitle;
	if(playSound){
		svc.alert.sound.play();
		if(soundTimeout){
			$timeout(function(){
				svc.alert.sound.stop();
			}, soundTimeout);
		}
	}
	svc.alert.show = true;
};
svc.close = function (){
	svc.alert.sound.stop();
	svc.alert.show = false;
	if(svc.alert.show_menu_on_close === true){
		svc.alert.show_menu_on_close = false;
		svc.goToMenu();
	}
};
`
